name: CI
on:
  push:
  pull_request:

jobs:
  java:
    runs-on: ubuntu-latest
    strategy:
      matrix: { module: [msUser, msQuizz] }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: mvn -B -q -f ${{ matrix.module }}/pom.xml -DskipTests package

  node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: msFront
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: msFront/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
